To read data from csv files

In [45]:
import pandas as pd
csv_1=pd.read_csv("C:\\Users\\chakr\\Desktop\\industry_sic.csv")
csv_1

     SIC Code                                        Description
0        1110  Growing of cereals (except rice), leguminous c...
1        1120                                    Growing of rice
2        1130  Growing of vegetables and melons, roots and tu...
3        1140                              Growing of sugar cane
4        1150                                 Growing of tobacco
..        ...                                                ...
726     98000                      Residents property management
727     98100  Undifferentiated goods-producing activities of...
728     98200  Undifferentiated service-producing activities ...
729     99000  Activities of extraterritorial organizations a...
730     99999                                    Dormant Company

[731 rows x 2 columns]

In [60]:
import pandas as pd
csv_2=pd.read_csv("C:\\Users\\chakr\\Desktop\\industry_sic.csv", nrows=1)

csv_2
print(type(csv_2))

# To get columns which is assingned to SIC Code
csv3=pd.read_csv("C:\\Users\\chakr\\Desktop\\industry_sic.csv", usecols=["SIC Code"])
csv3

csv_1

<class 'pandas.core.frame.DataFrame'>

     SIC Code                                        Description
0        1110  Growing of cereals (except rice), leguminous c...
1        1120                                    Growing of rice
2        1130  Growing of vegetables and melons, roots and tu...
3        1140                              Growing of sugar cane
4        1150                                 Growing of tobacco
..        ...                                                ...
726     98000                      Residents property management
727     98100  Undifferentiated goods-producing activities of...
728     98200  Undifferentiated service-producing activities ...
729     99000  Activities of extraterritorial organizations a...
730     99999                                    Dormant Company

[731 rows x 2 columns]

In [69]:
import pandas as pd
a=pd.read_csv("C:\\Users\\chakr\\Desktop\\industry_sic.csv",skiprows=[0,4])
a

      1110 Growing of cereals (except rice), leguminous crops and oil seeds
0     1120                                    Growing of rice
1     1130  Growing of vegetables and melons, roots and tu...
2     1150                                 Growing of tobacco
3     1160                             Growing of fibre crops
4     1190               Growing of other non-perennial crops
..     ...                                                ...
724  98000                      Residents property management
725  98100  Undifferentiated goods-producing activities of...
726  98200  Undifferentiated service-producing activities ...
727  99000  Activities of extraterritorial organizations a...
728  99999                                    Dormant Company

[729 rows x 2 columns]

In [72]:
a1=pd.read_csv("C:\\Users\\chakr\\Desktop\\industry_sic.csv",index_col="Description")
a1

                                                    SIC Code
Description
Growing of cereals (except rice), leguminous cr...      1110
Growing of rice                                         1120
Growing of vegetables and melons, roots and tubers      1130
Growing of sugar cane                                   1140
Growing of tobacco                                      1150
...                                                      ...
Residents property management                          98000
Undifferentiated goods-producing activities of ...     98100
Undifferentiated service-producing activities o...     98200
Activities of extraterritorial organizations an...     99000
Dormant Company                                        99999

[731 rows x 1 columns]

Header function implementation

In [76]:
import pandas as pd
a=pd.read_csv("C:\\Users\\chakr\\Desktop\\industry_sic.csv",header=3)
a

      1130 Growing of vegetables and melons, roots and tubers
0     1140                              Growing of sugar cane
1     1150                                 Growing of tobacco
2     1160                             Growing of fibre crops
3     1190               Growing of other non-perennial crops
4     1210                                  Growing of grapes
..     ...                                                ...
723  98000                      Residents property management
724  98100  Undifferentiated goods-producing activities of...
725  98200  Undifferentiated service-producing activities ...
726  99000  Activities of extraterritorial organizations a...
727  99999                                    Dormant Company

[728 rows x 2 columns]

In [80]:
a=a=pd.read_csv("C:\\Users\\chakr\\Desktop\\industry_sic.csv",names=["Col"])
a

                                                        Col
SIC Code                                        Description
1110      Growing of cereals (except rice), leguminous c...
1120                                        Growing of rice
1130      Growing of vegetables and melons, roots and tu...
1140                                  Growing of sugar cane
...                                                     ...
98000                         Residents property management
98100     Undifferentiated goods-producing activities of...
98200     Undifferentiated service-producing activities ...
99000     Activities of extraterritorial organizations a...
99999                                       Dormant Company

[732 rows x 1 columns]

Remove header

In [82]:
import pandas as pd
a=pd.read_csv("C:\\Users\\chakr\\Desktop\\industry_sic.csv",header=None)
a.head()

          0                                                  1
0  SIC Code                                        Description
1      1110  Growing of cereals (except rice), leguminous c...
2      1120                                    Growing of rice
3      1130  Growing of vegetables and melons, roots and tu...
4      1140                              Growing of sugar cane